export const DRAGGABLE_TYPE = {
  GROUP: 'GROUP',
  FIELD: 'FIELD',
  ADD_GROUP: 'ADD_GROUP',
  ADD_FIELD: 'ADD_FIELD',
};

export const SIDEBAR = {
  TOOLBOX: 'TOOLBOX',
  EDIT_COMPONENT: 'EDIT_COMPONENT',
};
